### ISSUE TITLE
[SUGGESTION] GUIless option

### ISSUE THREAD

**Issue by Ibotmealot** [Ximronno/Diore#7]
**Is your feature request related to a problem? Please describe.**
I find the GUI currently to be bulky and just too much, and in its current state, it lacks customization, such as in the item, etc. 

**Describe the solution you'd like**
Command-based experience, so /withdraw, /deposit, /balance, etc, and a config option for the GUI. Alternatively, if it's too much to deal with, both owners can easily make a GUI based on the commands with something like deluxe menus, for example.

**Comment by Ximronno** [comment]
Hello
My plugin already have commands for making transactions etc, check [wiki](https://github.com/Ximronno/Diore/wiki/Commands), the GUI only opens when using /balance and /balance info. I will add that server admins can deactivate GUI.
I will check Deluxe Menus, or other Menus plugins, like Slate, and rewrite Menus.
